### ISSUE TITLE
Kernel restarts on execution with no other warnings

### ISSUE THREAD

**Issue by Ramin-Zamani** [equinor/dlisio-notebooks#17]
Trying to load channels to numpy array, using the line below: 

curves60B = frame60B.curves()

Kernel restarts on its own with no other error messages.

**Comment by ErlendHaa** [comment]
Hi,

Do you have any other information? Did you modify the notebook in any way? Can you supply a minimal example that reproduces the kernel restart?

**Comment by erlendviggen** [comment]
And did you use the same Python package versions as specified in the `requirements.txt` file?

**Comment by Ramin-Zamani** [comment]
Double checked on Python version. I am using 3.7.3 
Here are minimum number of code lines that can reproduce the crash. 

# imports
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import dlisio
from dlisio import dlis
import pandas as pd
import numpy as np
import scipy.signal as signal
import logging
import copy

# load DLIS
with dlis.load('input_s1.DLIS') as (f, *tail):
    pass

# Extract Channels -----------------------------------
# utility functions defined
def index_of(frame):
    """Return the index channel of the frame"""
    return next(ch for ch in frame.channels if ch.name == frame.index)

def get_channel(frame, name):
    """Get a channel with a given name from a given frame; fail if the frame does not have exactly one such channel"""
    [channel] = [x for x in frame.channels if x.name == name]
    return channel

# Get 60B and its index channel
frame60B = f.object('FRAME', '60B')
index60B = index_of(frame60B)

# Check 
type(frame60B)

> dlisio.dlis.frame.Frame

# load into numpy array crashes here

curves60B = frame60B.curves()

**Comment by ErlendHaa** [comment]
```
with dlis.load('input_s1.DLIS') as (f, *tail):
pass
```

Using a with-statement like that will open- and immediately close the file again. Which is why the call to `curves` fail later on.

You either have to do all your file reading inside the with-statement scope or perhaps more convenient when working in notebooks, open the file without using python's `with`:

```
f, *tail = dlis.load('input_s1.DLIS')
```

Then the file handles are kept open until you explicitly call `.close()` on them.


Ideally dlisio should fail more gracefully when trying to operate on a closed file handle.

**Comment by Ramin-Zamani** [comment]
Thanks for your replies. Your comments helped me resolve the issue.
